---

- name: Java installation
  dnf:
    name: "openjdk-{{ elastic.openjdk_version }}-jre-headless"
    state: present

- name: install public key
  rpm_key:
    key: "https://{{ elastic.url }}/GPG-KEY-elasticsearch"
    state: present

- name: Add repository
  yum_repository:
    name: elasticsearch
    baseurl: https://{{ elastic.url }}/packages/8.x/yum
    gpgcheck: yes
    gpgkey: https://{{ elastic.url }}/GPG-KEY-elasticsearch
    enabled: yes
    state: present

- name: install packages
  yum:
    name: "{{ item }}"
    state: present
  loop:
    - "{{ elastic.packages }}"
